version: 2
updates:
  - package-ecosystem: pip
    directory: "/requirements"
    schedule:
      interval: monthly
      time: "04:00"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
